from __future__ import annotations

from .scenes.Beechwood_0_int import beechwood0IntfullSceneCfg, beechwood0IntquickSceneCfg
from .scenes.Benevolence_1_int import benevolence1IntfullSceneCfg, benevolence1IntquickSceneCfg
from .scenes.house_double_floor_lower import houseDoubleFloorLowerfullSceneCfg, houseDoubleFloorLowerquickSceneCfg
from .scenes.Ihlen_0_int import ihlen0IntfullSceneCfg, ihlen0IntquickSceneCfg
from .scenes.Merom_1_int import merom1IntfullSceneCfg, merom1IntquickSceneCfg
from .scenes.Pomaria_0_int import pomaria0IntfullSceneCfg, pomaria0IntquickSceneCfg
from .scenes.Beechwood_1_int import beechwood1IntfullSceneCfg, beechwood1IntquickSceneCfg
from .scenes.Benevolence_2_int import benevolence2IntfullSceneCfg, benevolence2IntquickSceneCfg
from .scenes.house_double_floor_upper import houseDoubleFloorUpperfullSceneCfg, houseDoubleFloorUpperquickSceneCfg
from .scenes.Ihlen_1_int import ihlen1IntfullSceneCfg, ihlen1IntquickSceneCfg
from .scenes.office_large import officeLargefullSceneCfg, officeLargequickSceneCfg
from .scenes.Pomaria_1_int import pomaria1IntfullSceneCfg, pomaria1IntquickSceneCfg
from .scenes.Rs_int import rsIntfullSceneCfg, rsIntquickSceneCfg
from .scenes.Benevolence_0_int import benevolence0IntfullSceneCfg, benevolence0IntquickSceneCfg
from .scenes.grocery_store_cafe import groceryStoreCafefullSceneCfg, groceryStoreCafequickSceneCfg
from .scenes.house_single_floor import houseSingleFloorfullSceneCfg, houseSingleFloorquickSceneCfg
from .scenes.Merom_0_int import merom0IntfullSceneCfg, merom0IntquickSceneCfg
from .scenes.Pomaria_0_garden import pomaria0GardenfullSceneCfg, pomaria0GardenquickSceneCfg
from .scenes.Pomaria_2_int import pomaria2IntfullSceneCfg, pomaria2IntquickSceneCfg
from .scenes.Wainscott_0_int import wainscott0IntfullSceneCfg, wainscott0IntquickSceneCfg
from .scenes.restaurant_brunch import restaurantBrunchfullSceneCfg, restaurantBrunchquickSceneCfg
from .scenes.Wainscott_1_int import wainscott1IntfullSceneCfg, wainscott1IntquickSceneCfg

